# Docker Compose Configuration
# visit https://docs.docker.com/compose/

version: '3.8'
services:
  nginx-reverse-proxy:
    image: nginx:alpine
    container_name: reverse-proxy
    hostname: reverse-proxy
    tty: true
    stdin_open: true
    restart: "unless-stopped"

    volumes:
      - ./nginx/config.template:/etc/nginx/conf.d/default.conf

    ports:
      - 80:80
      - 443:443

    networks:
      - api-network

    depends_on:
      - app

  # app service for your backend
  app:
    container_name: best-shop-container
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DB: bse-db # DATABASE_NAME
      DB_USER: # DATABASE_USER
      DB_PASS: # DATABASE_PASS
      DB_URI: mongodb://database:27017/bse-db
    ports:
      - '3000:3000'
    networks:
      - api-network
      - db-network
    depends_on:
      - database

  # start the mongodb service as container
  database:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: # DATABASE_NAME
      MONGO_INITDB_ROOT_PASSWORD: # DATABASE_USER
    networks:
      - db-network

networks:
  api-network:
    driver: bridge

  db-network:
    driver: bridge
